### ISSUE TITLE
Find a way to fix the flacky test

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#174]
Randomly, the CI makes the tests fails
see: https://github.com/meilisearch/meilisearch-dotnet/runs/3896895492

```
√ Meilisearch.Tests.IndexTests.UpdatePrimaryKey [18ms]
[xUnit.net 00:00:03.15]     Meilisearch.Tests.MeilisearchClientTests.GetDumpStatusById [FAIL]
[xUnit.net 00:00:03.15]       Expected dumpStatus.Status to be "done" with a length of 4, but "in_progress" has a length of 11, differs near "in_" (index 0).
[xUnit.net 00:00:03.15]       Stack Trace:
[xUnit.net 00:00:03.15]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[xUnit.net 00:00:03.15]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[xUnit.net 00:00:03.16]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[xUnit.net 00:00:03.16]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:03.16]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:03.16]            at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences()
[xUnit.net 00:00:03.16]            at FluentAssertions.Primitives.StringValidator.Validate()
[xUnit.net 00:00:03.16]            at FluentAssertions.Primitives.StringAssertions`1.Be(String expected, String because, Object[] becauseArgs)
[xUnit.net 00:00:03.16]         /home/runner/work/meilisearch-dotnet/meilisearch-dotnet/tests/Meilisearch.Tests/MeilisearchClientTests.cs(87,0): at Meilisearch.Tests.MeilisearchClientTests.GetDumpStatusById()
[xUnit.net 00:00:03.16]         --- End of stack trace from previous location where exception was thrown ---
```

The dump creation is not finished and that's why the dump fails.
We should find a way to avoid this random failure.

**Comment by sander1095** [comment]
Done! 🥳  #175

**Comment by Vivek-abstract** [comment]
@curquiza I read through the docs and it seems like the POST call to /dumps only initiates the dump creation process. It can complete in any x amount of time so testing that it has a status of "done" would fail. Instead we can test for the three available statuses "inprogress", "failed" and "done". What do you think?

I tried recreating this scenario locally by repeating the test a 100 times locally and you can see it only ran successfully 2 times out of 100
![image](https://user-images.githubusercontent.com/9103920/137514688-126a0b9b-6250-432c-81de-2041f3daac2b.png)

I've created https://github.com/meilisearch/meilisearch-dotnet/pull/177 to fix this by testing all three statuses.
