### ISSUE TITLE
Databasesize should not be int since it can be larger than what int32 supports

### ISSUE THREAD

**Issue by Fronix** [meilisearch/meilisearch-dotnet#494]
**Description**
When using `client.GetStatsAsync()` if the databaseize is too large it can't be serialized. I should not have to write custom converters to handle this.

**Expected behavior**
I expect databasesize to be a long to support larger numbers so it can be serialized.

**Current behavior**
Not able to use the `GetStatsAsync()` function due to this.

**Screenshots or Logs**
```
[16:26:41 ERR] Error getting Meilisearch stats
Newtonsoft.Json.JsonReaderException: JSON integer 7037943808 is too large or small for an Int32. Path 'databaseSize', line 1, position 26.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IvoRegister.Controllers.Common.Meilisearch.MeilisearchSettingsController.GetMeilisearchStatsAsync()
```

**Environment (please complete the following information):**
- OS: Windows 10
- Meilisearch version: 1.3.1
- meilisearch-dotnet version: 0.14.5

**Comment by curquiza** [comment]
hello @Fronix 

thanks for the report. this is indeed a bug.

We accept a PR to fix this bug 👍
